# Site settings
title: "Jacob Richeimer"
email: j.richeimer@gmail.com
description: "My personal website"
baseurl: ""
url: "https://jricheimer.github.io"
title_description: "master"
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-20365477-4"
# disqus_account: cartenoire
github_repository: https://github.com/jricheimer/jricheimer.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  jricheimer
linkedin_link: https://www.linkedin.com/in/jacob-richeimer-03028122/


# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
